### ISSUE TITLE
Auth URL needs to be updated

### ISSUE THREAD

**Issue by ardeay** [javierjulio/zesty-rb#1]
https://github.com/javierjulio/zesty-rb/blob/75dce693c44fae40e04ed01818b1947409bfcf98/lib/zesty/auth.rb#L4

Please update that AUTH url to

`https://auth.api.zesty.io`

**Comment by javierjulio** [comment]
@ardeay thanks! I'm working on updating auth specs and later the client ones to use that. 

In the meantime, what about **publishing** since it uses the same base URL?

https://github.com/javierjulio/zesty-rb/blob/17b2dab85cffb06330ada6406b8ee2b9b043d510/lib/zesty/client.rb#L65

**Comment by ardeay** [comment]
@javierjulio publishing will remain the same for the time being, we will post another update for you in April with the new urls for publishing.

**Comment by javierjulio** [comment]
@ardeay I plan to do an update tomorrow for the auth URL.

Any update yet on the publishing URL question from earlier in this issue?
